name: rust test (ubuntu)

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build executable
      run: cargo build

    - name: run tests
      run: cargo test --verbose
